"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Header } from "@/components/Header";
import { Heatmap } from "@/components/Heatmap";
import { PnlChart } from "@/components/PnlChart";
import { PositionsTable } from "@/components/PositionsTable";
import { TradeBar } from "@/components/TradeBar";
import { Watchlist } from "@/components/Watchlist";
import { deriveHeatmapItems } from "@/lib/heatmap";
import { derivePortfolioValue, derivePositionRows } from "@/lib/portfolio";
import { usePriceHistory } from "@/lib/usePriceHistory";
import { usePriceStream } from "@/lib/usePriceStream";
import type { PortfolioSnapshot, PortfolioSnapshotPoint, WatchlistEntry } from "@/lib/types";

export default function Home() {
  const [watchlist, setWatchlist] = useState<WatchlistEntry[] | null>(null);
  const [portfolio, setPortfolio] = useState<PortfolioSnapshot | null>(null);
  const [portfolioHistory, setPortfolioHistory] = useState<PortfolioSnapshotPoint[] | null>(null);
  const [selectedTicker, setSelectedTicker] = useState<string | null>(null);
  const { prices, status } = usePriceStream();

  const fetchPortfolio = useCallback(() => {
    fetch("/api/portfolio")
      .then((response) => {
        if (!response.ok) throw new Error(`portfolio fetch failed: ${response.status}`);
        return response.json();
      })
      .then((snapshot: PortfolioSnapshot) => setPortfolio(snapshot))
      .catch((error: unknown) => {
        // Keep the last good snapshot rather than clearing to null/zero — a
        // zeroed money figure is actively misleading, unlike an empty
        // watchlist. Matches the SSE resilience precedent from Phase 1.
        console.error(error);
      });
  }, []);

  const fetchPortfolioHistory = useCallback(() => {
    fetch("/api/portfolio/history")
      .then((response) => {
        if (!response.ok) throw new Error(`portfolio history fetch failed: ${response.status}`);
        return response.json();
      })
      .then((points: PortfolioSnapshotPoint[]) => setPortfolioHistory(points))
      .catch((error: unknown) => {
        // Same resilience choice as fetchPortfolio: keep the last successful
        // series rather than clearing it on a failed refetch.
        console.error(error);
      });
  }, []);

  function handleTraded() {
    fetchPortfolio();
    fetchPortfolioHistory();
  }

  useEffect(() => {
    fetch("/api/watchlist")
      .then((response) => {
        if (!response.ok) throw new Error(`watchlist fetch failed: ${response.status}`);
        return response.json();
      })
      .then((entries: WatchlistEntry[]) => setWatchlist(entries))
      .catch((error: unknown) => {
        console.error(error);
        setWatchlist([]);
      });
  }, []);

  useEffect(() => {
    fetchPortfolio();
  }, [fetchPortfolio]);

  useEffect(() => {
    fetchPortfolioHistory();
  }, [fetchPortfolioHistory]);

  const { cash, totalValue } = useMemo(
    () => derivePortfolioValue(portfolio, prices),
    [portfolio, prices],
  );

  const positionRows = useMemo(
    () => derivePositionRows(portfolio, prices),
    [portfolio, prices],
  );

  const heatmapItems = useMemo(() => deriveHeatmapItems(positionRows), [positionRows]);

  const watchlistTickers = useMemo(
    () => watchlist?.map((entry) => entry.ticker) ?? [],
    [watchlist],
  );
  const history = usePriceHistory(prices, watchlistTickers);

  function handleAdded(entry: WatchlistEntry) {
    setWatchlist((current) => [...(current ?? []), entry]);
  }

  async function handleRemove(ticker: string): Promise<boolean> {
    try {
      const response = await fetch(`/api/watchlist/${ticker}`, { method: "DELETE" });
      if (!response.ok) return false;
      const body = (await response.json()) as { removed: boolean };
      if (body.removed) {
        // Removing a ticker touches only watchlist state — no portfolio
        // refetch, no cash/position mutation on this path.
        setWatchlist((current) => (current ?? []).filter((entry) => entry.ticker !== ticker));
      }
      return true;
    } catch {
      return false;
    }
  }

  return (
    <div className="flex min-h-screen flex-col">
      <Header status={status} cash={cash} totalValue={totalValue} />
      <main className="flex flex-1 flex-col gap-4 px-6 pt-8 pb-8">
        <p className="text-body text-muted-foreground">
          Prices shown are generated by a market simulator, not live exchange data.
        </p>
        <TradeBar onTraded={handleTraded} />
        <Watchlist
          entries={watchlist}
          prices={prices}
          history={history}
          selectedTicker={selectedTicker}
          onSelectTicker={setSelectedTicker}
          onAdded={handleAdded}
          onRemove={handleRemove}
        />
        <Heatmap items={heatmapItems} />
        <PositionsTable rows={positionRows} />
        <PnlChart points={portfolioHistory} />
      </main>
    </div>
  );
}
