"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Header } from "@/components/Header";
import { PositionsTable } from "@/components/PositionsTable";
import { TradeBar } from "@/components/TradeBar";
import { Watchlist } from "@/components/Watchlist";
import { derivePortfolioValue, derivePositionRows } from "@/lib/portfolio";
import { usePriceHistory } from "@/lib/usePriceHistory";
import { usePriceStream } from "@/lib/usePriceStream";
import type { PortfolioSnapshot, WatchlistEntry } from "@/lib/types";

export default function Home() {
  const [watchlist, setWatchlist] = useState<WatchlistEntry[] | null>(null);
  const [portfolio, setPortfolio] = useState<PortfolioSnapshot | null>(null);
  const [selectedTicker, setSelectedTicker] = useState<string | null>(null);
  const { prices, status } = usePriceStream();

  const fetchPortfolio = useCallback(() => {
    fetch("/api/portfolio")
      .then((response) => {
        if (!response.ok) throw new Error(`portfolio fetch failed: ${response.status}`);
        return response.json();
      })
      .then((snapshot: PortfolioSnapshot) => setPortfolio(snapshot))
      .catch((error: unknown) => {
        // Keep the last good snapshot rather than clearing to null/zero — a
        // zeroed money figure is actively misleading, unlike an empty
        // watchlist. Matches the SSE resilience precedent from Phase 1.
        console.error(error);
      });
  }, []);

  useEffect(() => {
    fetch("/api/watchlist")
      .then((response) => {
        if (!response.ok) throw new Error(`watchlist fetch failed: ${response.status}`);
        return response.json();
      })
      .then((entries: WatchlistEntry[]) => setWatchlist(entries))
      .catch((error: unknown) => {
        console.error(error);
        setWatchlist([]);
      });
  }, []);

  useEffect(() => {
    fetchPortfolio();
  }, [fetchPortfolio]);

  const { cash, totalValue } = useMemo(
    () => derivePortfolioValue(portfolio, prices),
    [portfolio, prices],
  );

  const positionRows = useMemo(
    () => derivePositionRows(portfolio, prices),
    [portfolio, prices],
  );

  const watchlistTickers = useMemo(
    () => watchlist?.map((entry) => entry.ticker) ?? [],
    [watchlist],
  );
  const history = usePriceHistory(prices, watchlistTickers);

  function handleAdded(entry: WatchlistEntry) {
    setWatchlist((current) => [...(current ?? []), entry]);
  }

  return (
    <div className="flex min-h-screen flex-col">
      <Header status={status} cash={cash} totalValue={totalValue} />
      <main className="flex flex-1 flex-col gap-4 px-6 pt-8 pb-8">
        <p className="text-body text-muted-foreground">
          Prices shown are generated by a market simulator, not live exchange data.
        </p>
        <TradeBar onTraded={fetchPortfolio} />
        <Watchlist
          entries={watchlist}
          prices={prices}
          history={history}
          selectedTicker={selectedTicker}
          onSelectTicker={setSelectedTicker}
          onAdded={handleAdded}
        />
        <PositionsTable rows={positionRows} />
      </main>
    </div>
  );
}
